# Easier navigation: .., ..., ~
alias ..='cd ..'
alias cd..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias ~='cd ~' # `cd` is probably faster to type though

# open text files with atom
# alias atom='open -a Atom'

# List only directories
alias lsd='ls -lhF -G | grep --color=never "^d"'
# list all with details
# ig colors are not enabled by default and you want it colored, add -G on Os-X or --color on Linux
alias lsa='ls -AlhF'

# Always enable colored `grep` output
# Note: `GREP_OPTIONS="--color=auto"` is deprecated, hence the alias usage.
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# quicklook a file
alias qlf='qlmanage -p "$@" > /dev/null'

# toggle file visibility
alias saf='defaults write com.apple.finder AppleShowAllFiles ON && killall Finder'
alias haf='defaults write com.apple.finder AppleShowAllFiles OFF && killall Finder'

# Clean up LaunchServices to remove duplicates in the “Open With” menu
alias lscleanup="/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user"


# IP addresses
alias ip='dig +short myip.opendns.com @resolver1.opendns.com'
alias localip='ipconfig getifaddr en1'
alias ips='ifconfig -a | perl -nle"/(\d+\.\d+\.\d+\.\d+)/ && print $1"'

# update git
alias gs='echo ""; echo "*********************************************"; echo -e "   DO NOT FORGET TO PULL BEFORE COMMITTING"; echo "*********************************************"; echo ""; git status'
alias ga='git add'
alias gaa='git add .'
alias gc='git commit'
alias gcm='git commit -m'
alias gp='git pull'
alias gps='git push'
